// Type sources, in order of preference:
//
// 1. Generated (./generated/) - everything that mirrors a wire DTO in the
//    Rust backend (src/server.rs, src/commands/*.rs, src/error.rs).
//    Regenerated by ts-rs on every `cargo test` run; do not edit by hand.
// 2. Nothing else - as of the ts-rs integration there are no remaining
//    handwritten wire types in this file.
//
// Note on casing: the device-facing DTOs (DeviceStatus, WifiNetwork, ...)
// use camelCase via `#[serde(rename_all = "camelCase")]` in Rust, while the
// server-backed DTOs (Alarm, Todo, Channel, InboxItem, ...) intentionally
// have no rename attribute in Rust - they deserialize the server's
// snake_case JSON and Tauri forwards it to the UI unchanged - so their
// generated fields are snake_case.

export type { Alarm } from "./generated/Alarm";
export type { AlarmInput } from "./generated/AlarmInput";
export type { AppError } from "./generated/AppError";
export type { Channel } from "./generated/Channel";
export type { ChannelCreated } from "./generated/ChannelCreated";
export type { ConnectionStateInfo } from "./generated/ConnectionStateInfo";
export type { ContentSnapshot } from "./generated/ContentSnapshot";
export type { Device } from "./generated/Device";
export type { DeviceCommandResult } from "./generated/DeviceCommandResult";
export type { DeviceStatus } from "./generated/DeviceStatus";
export type { Importance } from "./generated/Importance";
export type { InboxItem } from "./generated/InboxItem";
export type { LogEntry } from "./generated/LogEntry";
export type { LogLevel } from "./generated/LogLevel";
export type { Repeat } from "./generated/Repeat";
export type { Todo } from "./generated/Todo";
export type { TodoDue } from "./generated/TodoDue";
export type { TodoInput } from "./generated/TodoInput";
export type { WifiNetwork } from "./generated/WifiNetwork";
